#![allow(clippy::expect_used)]

use std::env;
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let migrations_dir = manifest_dir.join("../resources/database/migrations");
    let migrations_dir = migrations_dir
        .canonicalize()
        .expect("resolve migrations directory");

    println!("cargo:rerun-if-changed={}", migrations_dir.display());

    let mut entries: Vec<_> = fs::read_dir(&migrations_dir)
        .expect("read migrations directory")
        .filter_map(|entry| entry.ok())
        .filter(|entry| {
            entry
                .path()
                .extension()
                .is_some_and(|extension| extension == "sql")
        })
        .collect();
    entries.sort_by_key(|entry| entry.file_name());

    let mut output = String::from(
        "// @generated by build.rs — do not edit by hand.\n\
         pub const EMBEDDED_MIGRATIONS: &[(&str, &str)] = &[\n",
    );

    for entry in &entries {
        let path = entry.path();
        let version = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .expect("migration filename");
        if !version.chars().next().is_some_and(|ch| ch.is_ascii_digit()) {
            panic!(
                "migration file {} must start with a numeric version prefix",
                path.display()
            );
        }
        let file_name = path
            .file_name()
            .and_then(|name| name.to_str())
            .expect("migration filename");
        writeln!(
            output,
            "    (\n        \"{version}\",\n        include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \
             \"/../resources/database/migrations/{file_name}\")),\n    ),"
        )
        .expect("write migration entry");
    }

    output.push_str("];\n");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR");
    fs::write(Path::new(&out_dir).join("embedded_migrations.rs"), output)
        .expect("write embedded migrations");
}
