#!/bin/sh
set -e

POST_INSTALL=/usr/share/robominer/package-post-install.sh

case "$1" in
    configure|abort-upgrade|abort-deconfigure|abort-remove)
        "$POST_INSTALL" configure-pre
        ;;
esac

#DEBHELPER#

case "$1" in
    configure|abort-upgrade|abort-deconfigure|abort-remove)
        "$POST_INSTALL" configure-post
        ;;
esac

exit 0
