[package]
name = "robominer-test-support"
version.workspace = true
rust-version.workspace = true
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
robominer-db = { workspace = true }
robominer-domain = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }

[lints]
workspace = true
