#!/usr/bin/env bash

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
INSTALL_PREFIX="/opt/robominer"
CONFIG_DIR="/etc/robominer"
SHARED_ENV_FILE="${CONFIG_DIR}/robominer.env"
SHARED_CONFIG_FILE="${CONFIG_DIR}/robominer.conf"
LEGACY_CONFIG_FILE="${CONFIG_DIR}/robominer-engine.conf"
STATIC_ROOT="${INSTALL_PREFIX}/static"
SYSUSERS_SOURCE="${ROOT}/deploy/systemd/robominer-engine.sysusers"

run_as_root() {
    if [[ "${EUID}" -eq 0 ]]; then
        "$@"
    else
        sudo "$@"
    fi
}

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "Required command not found: $1" >&2
        exit 1
    fi
}

create_service_user() {
    if [[ "${SKIP_USER:-false}" == true ]]; then
        echo "Skipping service account creation."
        return
    fi

    if getent passwd robominer >/dev/null 2>&1; then
        echo "Service account robominer already exists."
    elif command -v systemd-sysusers >/dev/null 2>&1; then
        echo "Creating service account with systemd-sysusers..."
        run_as_root install -D -m 0644 "${SYSUSERS_SOURCE}" /etc/sysusers.d/robominer-engine.conf
        run_as_root systemd-sysusers /etc/sysusers.d/robominer-engine.conf
    else
        echo "Creating service account with useradd..."
        run_as_root useradd --system --home-dir /var/lib/robominer --shell /usr/sbin/nologin robominer
    fi

    run_as_root install -d -o robominer -g robominer -m 0750 "${INSTALL_PREFIX}"
}

ensure_shared_config_file() {
    if [[ "${SKIP_CONFIG:-false}" == true ]]; then
        echo "Skipping config file creation."
        return
    fi

    run_as_root install -d -o root -g robominer -m 0750 "${CONFIG_DIR}"

    if [[ -f "${SHARED_ENV_FILE}" ]]; then
        echo "Environment file already exists: ${SHARED_ENV_FILE}"
        return
    fi

    if [[ -n "${ROBOMINER_DATABASE_URL:-}" ]]; then
        echo "Creating ${SHARED_ENV_FILE} from ROBOMINER_DATABASE_URL..."
        write_env_file_from_vars
        return
    fi

    if [[ -n "${ROBOMINER_DB_SERVER:-}" && -n "${ROBOMINER_DB_USER:-}" && -n "${ROBOMINER_DB_PASSWORD:-}" && -n "${ROBOMINER_DB_DATABASE:-}" ]]; then
        echo "Creating ${SHARED_ENV_FILE} from ROBOMINER_DB_* variables..."
        ROBOMINER_DATABASE_URL="mysql://${ROBOMINER_DB_USER}:${ROBOMINER_DB_PASSWORD}@${ROBOMINER_DB_SERVER}/${ROBOMINER_DB_DATABASE}"
        export ROBOMINER_DATABASE_URL
        write_env_file_from_vars
        return
    fi

    if [[ -f "${SHARED_CONFIG_FILE}" ]]; then
        echo "Legacy shared config already exists: ${SHARED_CONFIG_FILE}"
        echo "Prefer migrating to ${SHARED_ENV_FILE} (see deploy/systemd/robominer.env.example)."
        return
    fi

    if [[ -f "${LEGACY_CONFIG_FILE}" ]]; then
        echo "Migrating ${LEGACY_CONFIG_FILE} to ${SHARED_CONFIG_FILE}..."
        run_as_root cp "${LEGACY_CONFIG_FILE}" "${SHARED_CONFIG_FILE}"
        run_as_root chown root:robominer "${SHARED_CONFIG_FILE}"
        run_as_root chmod 0640 "${SHARED_CONFIG_FILE}"
        echo "Legacy conf kept for compatibility; prefer ${SHARED_ENV_FILE} going forward."
        return
    fi

    cat <<EOF
No RoboMiner config found under ${CONFIG_DIR}.

Preferred: create ${SHARED_ENV_FILE} (see deploy/systemd/robominer.env.example), for example:
  sudo install -d -m 0750 -o root -g robominer ${CONFIG_DIR}
  sudo cp deploy/systemd/robominer.env.example ${SHARED_ENV_FILE}
  sudoedit ${SHARED_ENV_FILE}
  sudo chown root:robominer ${SHARED_ENV_FILE}
  sudo chmod 0640 ${SHARED_ENV_FILE}

Or rerun an install script with ROBOMINER_DATABASE_URL or ROBOMINER_DB_* set.

Legacy key/value ${SHARED_CONFIG_FILE} still works but is deprecated and will be removed in a major release.
EOF
}

write_env_file_from_vars() {
    local host="${HOST:-${ROBOMINER_WEB_HOST:-127.0.0.1}}"
    local port="${PORT:-${ROBOMINER_WEB_PORT:-8080}}"
    local allow_signup="${ROBOMINER_ALLOW_SIGNUP:-0}"
    local secure_cookies="${ROBOMINER_SECURE_COOKIES:-0}"
    local trust_proxy="${ROBOMINER_TRUST_PROXY:-0}"
    local session_secret="${ROBOMINER_SESSION_SECRET:-}"
    local web_root="${ROBOMINER_WEB_ROOT:-${STATIC_ROOT}}"

    run_as_root tee "${SHARED_ENV_FILE}" >/dev/null <<EOF
# Generated by deploy/systemd install scripts. Prefer this over robominer.conf.
ROBOMINER_DATABASE_URL=${ROBOMINER_DATABASE_URL}
HOST=${host}
PORT=${port}
ROBOMINER_WEB_ROOT=${web_root}
ROBOMINER_ALLOW_SIGNUP=${allow_signup}
ROBOMINER_SECURE_COOKIES=${secure_cookies}
ROBOMINER_TRUST_PROXY=${trust_proxy}
EOF
    if [[ -n "${session_secret}" ]]; then
        printf 'ROBOMINER_SESSION_SECRET=%s\n' "${session_secret}" | run_as_root tee -a "${SHARED_ENV_FILE}" >/dev/null
    fi
    if [[ -n "${ROBOMINER_SESSION_TTL_SECS:-}" ]]; then
        printf 'ROBOMINER_SESSION_TTL_SECS=%s\n' "${ROBOMINER_SESSION_TTL_SECS}" | run_as_root tee -a "${SHARED_ENV_FILE}" >/dev/null
    elif [[ -n "${ROBOMINER_SESSION_TTL_HOURS:-}" ]]; then
        printf 'ROBOMINER_SESSION_TTL_HOURS=%s\n' "${ROBOMINER_SESSION_TTL_HOURS}" | run_as_root tee -a "${SHARED_ENV_FILE}" >/dev/null
    fi
    run_as_root chown root:robominer "${SHARED_ENV_FILE}"
    run_as_root chmod 0640 "${SHARED_ENV_FILE}"
}

env_file_has_key() {
    local key="$1"
    [[ -f "${SHARED_ENV_FILE}" ]] && grep -Eq "^${key}=" "${SHARED_ENV_FILE}"
}

ensure_web_config_keys() {
    if [[ "${SKIP_CONFIG:-false}" == true ]]; then
        return
    fi

    if [[ -f "${SHARED_ENV_FILE}" ]]; then
        local append=""
        if ! env_file_has_key HOST; then
            append+="HOST=${HOST:-${ROBOMINER_WEB_HOST:-127.0.0.1}}"$'\n'
        fi
        if ! env_file_has_key PORT; then
            append+="PORT=${PORT:-${ROBOMINER_WEB_PORT:-8080}}"$'\n'
        fi
        if ! env_file_has_key ROBOMINER_WEB_ROOT; then
            append+="ROBOMINER_WEB_ROOT=${ROBOMINER_WEB_ROOT:-${STATIC_ROOT}}"$'\n'
        fi
        if [[ -n "${ROBOMINER_SESSION_SECRET:-}" ]] && ! env_file_has_key ROBOMINER_SESSION_SECRET; then
            append+="ROBOMINER_SESSION_SECRET=${ROBOMINER_SESSION_SECRET}"$'\n'
        fi
        if [[ "${ROBOMINER_SECURE_COOKIES:-}" == "1" ]] && ! env_file_has_key ROBOMINER_SECURE_COOKIES; then
            append+="ROBOMINER_SECURE_COOKIES=1"$'\n'
        fi
        if ! env_file_has_key ROBOMINER_ALLOW_SIGNUP; then
            append+="ROBOMINER_ALLOW_SIGNUP=${ROBOMINER_ALLOW_SIGNUP:-0}"$'\n'
        fi
        if [[ -n "${ROBOMINER_SESSION_TTL_SECS:-}" ]] && ! env_file_has_key ROBOMINER_SESSION_TTL_SECS; then
            append+="ROBOMINER_SESSION_TTL_SECS=${ROBOMINER_SESSION_TTL_SECS}"$'\n'
        elif [[ -n "${ROBOMINER_SESSION_TTL_HOURS:-}" ]] && ! env_file_has_key ROBOMINER_SESSION_TTL_HOURS; then
            append+="ROBOMINER_SESSION_TTL_HOURS=${ROBOMINER_SESSION_TTL_HOURS}"$'\n'
        fi
        if [[ -n "${append}" ]]; then
            echo "Adding web settings to ${SHARED_ENV_FILE}..."
            printf '%s' "${append}" | run_as_root tee -a "${SHARED_ENV_FILE}" >/dev/null
            run_as_root chown root:robominer "${SHARED_ENV_FILE}"
            run_as_root chmod 0640 "${SHARED_ENV_FILE}"
        fi
        return
    fi

    if [[ ! -f "${SHARED_CONFIG_FILE}" ]]; then
        return
    fi

    local append=""
    if ! grep -Eq '^[Hh][Oo][Ss][Tt][[:space:]]' "${SHARED_CONFIG_FILE}"; then
        append+="host ${ROBOMINER_WEB_HOST:-127.0.0.1}"$'\n'
    fi
    if ! grep -Eq '^[Pp][Oo][Rr][Tt][[:space:]]' "${SHARED_CONFIG_FILE}"; then
        append+="port ${ROBOMINER_WEB_PORT:-8080}"$'\n'
    fi
    if ! grep -Eq '^[Ww][Ee][Bb][Rr][Oo][Oo][Tt][[:space:]]' "${SHARED_CONFIG_FILE}"; then
        append+="webroot ${STATIC_ROOT}"$'\n'
    fi
    if [[ -n "${ROBOMINER_SESSION_SECRET:-}" ]] && ! grep -Eq '^[Ss][Ee][Ss][Ss][Ii][Oo][Nn][Ss][Ee][Cc][Rr][Ee][Tt][[:space:]]' "${SHARED_CONFIG_FILE}"; then
        append+="sessionsecret ${ROBOMINER_SESSION_SECRET}"$'\n'
    fi
    if [[ "${ROBOMINER_SECURE_COOKIES:-}" == "1" ]] && ! grep -Eq '^[Ss][Ee][Cc][Uu][Rr][Ee][Cc][Oo][Oo][Kk][Ii][Ee][Ss][[:space:]]' "${SHARED_CONFIG_FILE}"; then
        append+="securecookies 1"$'\n'
    fi
    if ! grep -Eq '^[Aa][Ll][Ll][Oo][Ww][Ss][Ii][Gg][Nn][Uu][Pp][[:space:]]' "${SHARED_CONFIG_FILE}"; then
        append+="allowsignup ${ROBOMINER_ALLOW_SIGNUP:-0}"$'\n'
    fi
    if [[ -n "${ROBOMINER_SESSION_TTL_SECS:-}" ]] && ! grep -Eq '^[Ss][Ee][Ss][Ss][Ii][Oo][Nn][Tt][Tt][Ll][Ss][Ee][Cc][Ss][[:space:]]' "${SHARED_CONFIG_FILE}"; then
        append+="sessionttlsecs ${ROBOMINER_SESSION_TTL_SECS}"$'\n'
    elif [[ -n "${ROBOMINER_SESSION_TTL_HOURS:-}" ]] && ! grep -Eq '^[Ss][Ee][Ss][Ss][Ii][Oo][Nn][Tt][Tt][Ll][Hh][Oo][Uu][Rr][Ss][[:space:]]' "${SHARED_CONFIG_FILE}"; then
        append+="sessionttlhours ${ROBOMINER_SESSION_TTL_HOURS}"$'\n'
    fi

    if [[ -n "${append}" ]]; then
        echo "Adding web settings to ${SHARED_CONFIG_FILE}..."
        printf '%s' "${append}" | run_as_root tee -a "${SHARED_CONFIG_FILE}" >/dev/null
        run_as_root chown root:robominer "${SHARED_CONFIG_FILE}"
        run_as_root chmod 0640 "${SHARED_CONFIG_FILE}"
    fi
}

config_is_ready() {
    [[ -f "${SHARED_ENV_FILE}" || -f "${SHARED_CONFIG_FILE}" || -n "${ROBOMINER_DATABASE_URL:-}" ]]
}

run_engine_with_config() {
    local engine_bin="$1"
    shift

    if [[ -f "${SHARED_ENV_FILE}" ]]; then
        run_as_root env bash -c '
            set -euo pipefail
            set -a
            # shellcheck disable=SC1090
            source "$1"
            set +a
            shift
            exec "$@"
        ' bash "${SHARED_ENV_FILE}" "${engine_bin}" "$@"
        return
    fi

    if [[ -n "${ROBOMINER_DATABASE_URL:-}" ]]; then
        run_as_root env ROBOMINER_DATABASE_URL="${ROBOMINER_DATABASE_URL}" "${engine_bin}" "$@"
        return
    fi

    if [[ -f "${SHARED_CONFIG_FILE}" ]]; then
        run_as_root "${engine_bin}" --config "${SHARED_CONFIG_FILE}" "$@"
        return
    fi

    echo "No RoboMiner database config found (expected ${SHARED_ENV_FILE} or ${SHARED_CONFIG_FILE})." >&2
    exit 1
}

install_static_assets() {
    echo "Installing static assets to ${STATIC_ROOT}..."
    run_as_root install -d -o robominer -g robominer -m 0755 "${STATIC_ROOT}/css"
    if command -v rsync >/dev/null 2>&1; then
        run_as_root rsync -a --delete \
            --chown=robominer:robominer \
            --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r \
            "${ROOT}/robominer-web/static/css/" "${STATIC_ROOT}/css/"
    else
        run_as_root find "${STATIC_ROOT}/css" -mindepth 1 -delete 2>/dev/null || true
        run_as_root cp -a "${ROOT}/robominer-web/static/css/." "${STATIC_ROOT}/css/"
        run_as_root chown -R robominer:robominer "${STATIC_ROOT}/css"
        run_as_root find "${STATIC_ROOT}/css" -type d -exec chmod 0755 {} +
        run_as_root find "${STATIC_ROOT}/css" -type f -exec chmod 0644 {} +
    fi

    # Page and rally JS (linked via <script src>, not inlined into HTML).
    run_as_root install -d -o robominer -g robominer -m 0755 "${STATIC_ROOT}/js"
    if command -v rsync >/dev/null 2>&1; then
        run_as_root rsync -a --delete \
            --chown=robominer:robominer \
            --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r \
            "${ROOT}/robominer-web/static/js/" "${STATIC_ROOT}/js/"
    else
        run_as_root find "${STATIC_ROOT}/js" -mindepth 1 -delete 2>/dev/null || true
        run_as_root cp -a "${ROOT}/robominer-web/static/js/." "${STATIC_ROOT}/js/"
        run_as_root chown -R robominer:robominer "${STATIC_ROOT}/js"
        run_as_root find "${STATIC_ROOT}/js" -type d -exec chmod 0755 {} +
        run_as_root find "${STATIC_ROOT}/js" -type f -exec chmod 0644 {} +
    fi
}

build_release_packages() {
    require_command cargo

    local -a cargo_args=()
    for package in "$@"; do
        cargo_args+=(-p "${package}")
    done

    echo "Building release packages: $*"
    (
        cd "${ROOT}"
        cargo build --release "${cargo_args[@]}"
    )
}

install_engine_binary() {
    local binary_dest="${INSTALL_PREFIX}/bin/robominer-engine"
    echo "Installing binary to ${binary_dest}..."
    run_as_root install -D -m 0755 "${ROOT}/target/release/robominer-engine" "${binary_dest}"
}

install_web_binary() {
    local binary_dest="${INSTALL_PREFIX}/bin/robominer-web"
    local health_dest="${INSTALL_PREFIX}/bin/robominer-wait-web-health"
    echo "Installing binary to ${binary_dest}..."
    run_as_root install -D -m 0755 "${ROOT}/target/release/robominer-web" "${binary_dest}"
    echo "Installing health waiter to ${health_dest}..."
    run_as_root install -D -m 0755 "${ROOT}/deploy/systemd/wait-web-health.sh" "${health_dest}"
}

install_systemd_units() {
    if [[ "${SKIP_SYSTEMD:-false}" == true ]]; then
        echo "Skipping systemd unit installation."
        return
    fi

    if [[ "$#" -eq 0 ]]; then
        return
    fi

    require_command systemctl

    local unit
    for unit in "$@"; do
        echo "Installing systemd unit ${unit}..."
        run_as_root install -D -m 0644 "${ROOT}/deploy/systemd/${unit}" \
            "/etc/systemd/system/${unit}"
    done

    run_as_root systemctl daemon-reload

    if [[ "${ENABLE_SERVICE:-false}" == true ]]; then
        if ! config_is_ready; then
            echo "Cannot enable services without ${SHARED_ENV_FILE}, ${SHARED_CONFIG_FILE}, or ROBOMINER_DATABASE_URL." >&2
            exit 1
        fi

        for unit in "$@"; do
            echo "Enabling and starting ${unit}..."
            run_as_root systemctl enable --now "${unit}"
            echo "Follow logs with: journalctl -u ${unit} -f"
        done
    else
        echo "Systemd units installed. Enable them with:"
        for unit in "$@"; do
            echo "  sudo systemctl enable --now ${unit}"
        done
    fi
}

engine_migrate_command() {
    if [[ -f "${SHARED_ENV_FILE}" || -n "${ROBOMINER_DATABASE_URL:-}" ]]; then
        echo "${INSTALL_PREFIX}/bin/robominer-engine migrate apply"
    else
        echo "${INSTALL_PREFIX}/bin/robominer-engine --config ${SHARED_CONFIG_FILE} migrate apply"
    fi
}

print_migrate_reminder() {
    cat <<EOF

Schema migrations are not applied by this install script.
After the database is reachable and ${SHARED_ENV_FILE} (preferred) or ${SHARED_CONFIG_FILE} is configured, run:

  sudo $(engine_migrate_command)

Check status with:

  sudo ${INSTALL_PREFIX}/bin/robominer-engine migrate status --check

(Legacy conf installs still need --config ${SHARED_CONFIG_FILE}.)

Or pass --migrate to this install script to run migrate before enabling services.
EOF
}

run_schema_migrate() {
    local engine_bin="${INSTALL_PREFIX}/bin/robominer-engine"

    if [[ ! -x "${engine_bin}" ]]; then
        echo "Cannot migrate: ${engine_bin} is not installed." >&2
        echo "Install the engine (omit --web-only) or run migrate from a host that has it." >&2
        exit 1
    fi
    if ! config_is_ready; then
        echo "Cannot migrate: missing ${SHARED_ENV_FILE}, ${SHARED_CONFIG_FILE}, or ROBOMINER_DATABASE_URL." >&2
        exit 1
    fi

    echo "Applying schema migrations..."
    run_engine_with_config "${engine_bin}" migrate apply
}
