#![allow(clippy::expect_used)]

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let animation_types = manifest_dir.join("src/animation/types.rs");
    println!("cargo:rerun-if-changed={}", animation_types.display());

    let source = fs::read_to_string(&animation_types).expect("read animation/types.rs");
    let current_version = parse_u32_const(&source, "ANIMATION_PAYLOAD_VERSION")
        .expect("ANIMATION_PAYLOAD_VERSION in animation/types.rs");
    let legacy_version = parse_u32_const(&source, "LEGACY_ANIMATION_PAYLOAD_VERSION").unwrap_or(1);

    let contract_js = format!(
        "// @generated by robominer-sim/build.rs — do not edit.\n\
         var ANIMATION_PAYLOAD_CURRENT_VERSION = {current_version};\n\
         var ANIMATION_PAYLOAD_SUPPORTED_VERSIONS = [{legacy_version}, {current_version}];\n"
    );

    let output_path =
        manifest_dir.join("../robominer-web/static/js/rally_animation/generated/contract.js");
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent).expect("create generated dir");
    }
    fs::write(&output_path, contract_js).expect("write animation contract.js");
}

fn parse_u32_const(source: &str, name: &str) -> Option<u32> {
    let needle = format!("pub const {name}: u32 = ");
    let start = source.find(&needle)? + needle.len();
    let rest = &source[start..];
    let end = rest.find(';')?;
    rest[..end].trim().parse().ok()
}

#[cfg(test)]
mod tests {
    use super::parse_u32_const;

    #[test]
    fn parse_u32_const_reads_animation_version() {
        let source = "pub const ANIMATION_PAYLOAD_VERSION: u32 = 2;\n";
        assert_eq!(
            parse_u32_const(source, "ANIMATION_PAYLOAD_VERSION"),
            Some(2)
        );
    }
}
