[package]
name = "robominer-domain"
version.workspace = true
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = { workspace = true }
robominer-db = { workspace = true }
robominer-program = { workspace = true }
robominer-sim = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["rt"] }

[dev-dependencies]
robominer-test-support = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serial_test = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
