[package]
name = "robominer-optimize"
version.workspace = true
rust-version.workspace = true
edition = "2024"
license = "MIT OR Apache-2.0"

[[bin]]
name = "robominer-optimize"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }
robominer-db = { workspace = true }
robominer-domain = { workspace = true }
robominer-program = { workspace = true }
robominer-sim = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
robominer-test-support = { workspace = true }

[lints]
workspace = true
