/// Names that cannot be used as user-defined function identifiers.
pub(super) fn is_reserved_name(name: &str) -> bool {
    matches!(
        name,
        "fn" | "return"
            | "if"
            | "else"
            | "while"
            | "do"
            | "const"
            | "int"
            | "double"
            | "float"
            | "bool"
            | "true"
            | "false"
            | "move"
            | "rotate"
            | "mine"
            | "dump"
            | "dumpA"
            | "dumpB"
            | "dumpC"
            | "scan"
            | "time"
            | "ore"
            | "oreDistance"
            | "oreType"
            | "abs"
            | "sqrt"
            | "sin"
            | "cos"
            | "tan"
            | "min"
            | "max"
            | "robot"
            | "area"
    )
}
